# Generated by Django 4.0 on 2022-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='upload a category image', null=True, upload_to='images/', verbose_name='category image'),
        ),
    ]
