# Generated by Django 4.0.1 on 2022-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_brand_alter_product_descount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
