# Generated by Django 4.0.1 on 2022-01-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order_cod_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('txn_id', models.CharField(max_length=200)),
                ('txn_amt', models.CharField(max_length=20)),
                ('txn_date', models.CharField(max_length=50)),
                ('bank_txn_id', models.CharField(max_length=30)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
            ],
        ),
    ]
