# Generated by Django 4.0.1 on 2022-02-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contact_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customer'),
        ),
    ]
